# Cloud Build 配置檔
steps:
# 步驟 1: 建置 Docker 映像
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/mnews-personal-ads:$COMMIT_SHA', '.']

# 步驟 2: 推送 Docker 映像到 Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/mnews-personal-ads:$COMMIT_SHA']

# 步驟 3: 部署到 Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run',
         'deploy',
         'mnews-personal-ads',  # 替換為你的 Cloud Run 服務名稱
         '--image', 'gcr.io/$PROJECT_ID/mnews-personal-ads:$COMMIT_SHA',
         '--region', 'asia-east1',  # 替換為你的 Cloud Run 區域
         '--platform', 'managed',
         '--allow-unauthenticated',
         '--use-http2'] # 新增此行以啟用 HTTP/2

images:
- 'gcr.io/$PROJECT_ID/mnews-personal-ads:$COMMIT_SHA'
